### ISSUE TITLE
[new_school] ITCR

### ISSUE THREAD

**Issue by sGerli** [noahpresler/semesterly#1153]
Hi I'm trying to add ITCR (Instituto Tecnológico de Costa Rica) to Semesterly.

My fork: https://github.com/sGerli/semesterly/tree/itcr-school

So far I've built a parser that seems to be working ok.

After digesting the courses I tried testing the web app, but it isn't letting me select any course. Django is throwing the following error:

```
ERROR 2021-02-02 04:26:42 Internal Server Error: /timetables/
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
web_1       |     response = self.process_exception_by_middleware(e, request)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1       |     return view_func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/code/helpers/mixins.py", line 44, in dispatch
web_1       |     return super(ValidateSubdomainMixin, self).dispatch(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 483, in dispatch
web_1       |     response = self.handle_exception(exc)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 443, in handle_exception
web_1       |     self.raise_uncaught_exception(exc)
web_1       |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 480, in dispatch
web_1       |     response = handler(request, *args, **kwargs)
web_1       |   File "/code/timetable/views.py", line 93, in post
web_1       |     opt_course_ids)]
web_1       |   File "/code/timetable/utils.py", line 56, in courses_to_timetables
web_1       |     return sorted(timetables, key=lambda tt: get_tt_cost(tt, sort_metrics))
web_1       |   File "/code/timetable/utils.py", line 93, in slots_to_timetables
web_1       |     day_to_usage = get_day_to_usage(custom_events, school)
web_1       |   File "/code/timetable/utils.py", line 215, in get_day_to_usage
web_1       |     for day in ['M', 'T', 'W', 'R', 'F']
web_1       |   File "/code/timetable/utils.py", line 215, in <dictcomp>
web_1       |     for day in ['M', 'T', 'W', 'R', 'F']
web_1       | KeyError: u''
web_1       | [02/Feb/2021 04:26:42] "POST /timetables/ HTTP/1.1" 500 15279
```

**Comment by sGerli** [comment]
I think I figured that one out. Some of the section meeting times where on weekends.

**Comment by Boccca2014** [comment]
Hi @sGerli,

This repository is now deprecated as of June 2021.
The new repository can be found [HERE](https://github.com/jhuopensource/semesterly).
If you still wish to integrate your university, note any issues, or make any suggestions, please place them in the new repository. Thank you!

Best,

Sebastian (@Boccca2014)
Current Program Manager of [Semester.ly](https://semester.ly/)
